import { mkdir, rename, rm } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";

import type { ClusterConfig, InstanceConfig } from "./types";
import { instanceDir, managedInstances, root } from "./config";
import * as papermc from "./services/papermc";
import { readForwardingSecret } from "./proxy";
import { nextFreePort } from "./ports";
import { getConfValue, setConfValue } from "./confedit";

/** Parse "1.21.11-127-bd74bf6 (MC: 1.21.11)" from version_history.json. */
export async function detectMcVersion(dir: string): Promise<string | undefined> {
	const path = join(dir, "version_history.json");

	if (!existsSync(path)) {
		return undefined;
	}

	try {
		const data = await Bun.file(path).json();
		const version = String(data.currentVersion ?? "").match(/MC:\s*([\d.]+)/);

		return version?.[1];
	} catch {
		return undefined;
	}
}

/** Minimal server.properties for a fresh backend — Paper fills in the rest on first boot. */
function serverPropertiesTemplate(port: number): string {
	return `#Minecraft server properties (generated by mrds)
server-port=${port}
server-ip=127.0.0.1
online-mode=false
motd=A Luna Minecraft Server
enforce-secure-profile=false
spawn-protection=0
view-distance=10
simulation-distance=10
max-players=64
enable-query=false
`;
}

/** Paper's velocity modern-forwarding block, keyed with the proxy's shared secret. */
function paperGlobalTemplate(secret: string): string {
	return `# Generated by mrds — paper merges in remaining defaults on first boot.
proxies:
  velocity:
    enabled: true
    online-mode: false
    secret: "${secret}"
`;
}

export interface CreateOptions {
	mcVersion: string;
	port?: number;
	memory?: string;
	profile?: string;
	register?: boolean;
}

export interface CreateResult {
	name: string;
	dir: string;
	port: number;
	build: papermc.BuildInfo;
}

/**
 * Lay down a new Paper backend: directory skeleton, newest build for the given
 * MC version, EULA, server.properties on a free port, and the proxy forwarding
 * config. Mutates cfg with the new registry entry (caller saves).
 */
export async function createInstance(
	cfg: ClusterConfig,
	name: string,
	opts: CreateOptions,
): Promise<CreateResult> {
	if (managedInstances(cfg)[name] || cfg.instances[name]) {
		throw new Error(`instance "${name}" already exists`);
	}

	if (!/^[a-z0-9_-]+$/.test(name)) {
		throw new Error("instance name must be lowercase alphanumeric/-/_");
	}

	const dir = join(root(), name);

	if (existsSync(dir)) {
		throw new Error(`directory ${dir} already exists`);
	}

	const port = opts.port ?? nextFreePort(cfg, cfg.serverPortRange);
	const build = await papermc.latestBuild("paper", opts.mcVersion);

	await mkdir(join(dir, "plugins"), { recursive: true });
	await mkdir(join(dir, "config"), { recursive: true });
	await papermc.downloadBuild(build, join(dir, "server.jar"));
	await Bun.write(join(dir, "eula.txt"), "eula=true\n");
	await Bun.write(join(dir, "server.properties"), serverPropertiesTemplate(port));

	const secret = await readForwardingSecret(cfg);

	await Bun.write(join(dir, "config", "paper-global.yml"), paperGlobalTemplate(secret));

	const inst: InstanceConfig = {
		dir: name,
		software: "paper",
		mcVersion: opts.mcVersion,
		port,
		memory: opts.memory ?? "2G",
		profile: opts.profile ?? "aikar",
		proxy: { register: opts.register ?? true },
	};

	cfg.instances[name] = inst;

	return { name, dir, port, build };
}

export interface SetVersionResult {
	from?: string;
	to: string;
	build: papermc.BuildInfo;
	backedUpJar: string;
}

/**
 * Swap an instance onto another Minecraft version, keeping the previous jar as
 * `.old` and rolling back to it if the download fails. Mutates cfg (caller saves).
 */
export async function setVersion(
	cfg: ClusterConfig,
	name: string,
	mcVersion: string,
): Promise<SetVersionResult> {
	const inst = managedInstances(cfg)[name];

	if (!inst) {
		throw new Error(`unknown instance: ${name}`);
	}

	const project = inst.software === "velocity" ? "velocity" : "paper";
	const build = await papermc.latestBuild(project, mcVersion);
	const jar = join(instanceDir(inst), inst.software === "velocity" ? "velocity.jar" : "server.jar");
	const backup = jar + ".old";

	if (existsSync(jar)) {
		await rm(backup, { force: true });
		await rename(jar, backup);
	}

	try {
		await papermc.downloadBuild(build, jar);
	} catch (err) {
		if (existsSync(backup)) {
			await rename(backup, jar);
		}

		throw err;
	}

	const from = inst.mcVersion;

	inst.mcVersion = mcVersion;

	return { from, to: mcVersion, build, backedUpJar: backup };
}

/** Change an instance's game port (server.properties + registry; caller runs proxy sync). */
export async function setPort(cfg: ClusterConfig, name: string, port: number): Promise<void> {
	const inst = managedInstances(cfg)[name];

	if (!inst) {
		throw new Error(`unknown instance: ${name}`);
	}

	if (inst.software === "paper") {
		const props = join(instanceDir(inst), "server.properties");

		if (!(await setConfValue(props, "properties", "server-port", port))) {
			throw new Error(`could not update server-port in ${props}`);
		}
	}

	inst.port = port;
}

/** Read one key from an instance's server.properties. */
export async function getServerProperty(
	cfg: ClusterConfig,
	name: string,
	key: string,
): Promise<string | undefined> {
	const inst = managedInstances(cfg)[name];

	if (!inst) {
		throw new Error(`unknown instance: ${name}`);
	}

	return await getConfValue(join(instanceDir(inst), "server.properties"), "properties", key);
}

/** Write one key into an instance's server.properties. False when the key is absent. */
export async function setServerProperty(
	cfg: ClusterConfig,
	name: string,
	key: string,
	value: string,
): Promise<boolean> {
	const inst = managedInstances(cfg)[name];

	if (!inst) {
		throw new Error(`unknown instance: ${name}`);
	}

	return await setConfValue(
		join(instanceDir(inst), "server.properties"),
		"properties",
		key,
		value,
	);
}

/**
 * Drop an instance from the registry, optionally deleting its directory too.
 * External instances are never purged — their files live on another machine.
 */
export async function deleteInstance(
	cfg: ClusterConfig,
	name: string,
	purge: boolean,
): Promise<{ purged: boolean }> {
	const inst = cfg.instances[name];

	if (!inst) {
		throw new Error(`unknown instance: ${name}`);
	}

	delete cfg.instances[name];

	if (purge && !inst.external) {
		await rm(instanceDir(inst), { recursive: true, force: true });
	}

	return { purged: purge };
}
