import { mkdir, readdir, rename, rm } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";

import type { ClusterConfig, InstanceConfig } from "./types";
import { instanceDir, managedInstances, root } from "./config";
import * as papermc from "./services/papermc";
import { readForwardingSecret } from "./proxy";
import { nextFreePort } from "./ports";
import { getConfValue, setConfValue } from "./confedit";
import { ProgressReporter } from "./progress";
import { SERVER_SETTINGS, validateJavaArgs, validateSettings } from "./settings";

/** Parse "1.21.11-127-bd74bf6 (MC: 1.21.11)" from version_history.json. */
export async function detectMcVersion(dir: string): Promise<string | undefined> {
	const path = join(dir, "version_history.json");

	if (!existsSync(path)) {
		return undefined;
	}

	try {
		const data = await Bun.file(path).json();
		const version = String(data.currentVersion ?? "").match(/MC:\s*([\d.]+)/);

		return version?.[1];
	} catch {
		return undefined;
	}
}

/**
 * server.properties for a fresh backend: every setting luna knows about, at the
 * value the caller asked for or at the schema's default. Paper fills in the keys
 * outside that list on first boot. The keys marked `managed` in the schema keep
 * their default whatever was requested — they are what makes velocity forwarding
 * work.
 *
 * `bindAddress` is the one managed key that is not a constant: a backend on the
 * primary's own machine is reached over loopback, but one on a follower has to
 * accept the proxy's connection across the LAN, so binding it to 127.0.0.1
 * would make it unreachable no matter what velocity.toml says.
 */
function serverPropertiesTemplate(
	port: number,
	settings: Record<string, string>,
	bindAddress: string,
): string {
	const values: Record<string, string> = {};

	for (const spec of SERVER_SETTINGS) {
		values[spec.key] = spec.managed ? spec.fallback : (settings[spec.key] ?? spec.fallback);
	}

	values["server-ip"] = bindAddress;
	values["server-port"] = String(port);
	values["enable-query"] = "false";

	const lines = Object.entries(values).map(([key, value]) => `${key}=${value}`);

	return `#Minecraft server properties (generated by luna)\n${lines.join("\n")}\n`;
}

/** Paper's velocity modern-forwarding block, keyed with the proxy's shared secret. */
function paperGlobalTemplate(secret: string): string {
	return `# Generated by luna — paper merges in remaining defaults on first boot.
proxies:
  velocity:
    enabled: true
    online-mode: false
    secret: "${secret}"
`;
}

export interface CreateOptions {
	mcVersion: string;
	port?: number;
	memory?: string;
	profile?: string;
	register?: boolean;
	/** server.properties values to write instead of the schema defaults */
	settings?: Record<string, string>;
	/** extra JVM flags for the generated run script */
	javaArgs?: string[];
	/** plugin groups beside "default" (which always applies) */
	pluginGroups?: string[];
	/** per-instance plugin overrides (plugin name → force-add/disable) */
	pluginOverrides?: Record<string, boolean>;
	/** daemon that will own the instance (absent = the primary's host) */
	daemon?: string;
	/** live progress for the caller's renderer */
	reporter?: ProgressReporter;
}

export interface CreateResult {
	name: string;
	dir: string;
	port: number;
	build: papermc.BuildInfo;
}

/**
 * Lay down a new Paper backend: directory skeleton, newest build for the given
 * MC version, EULA, server.properties on a free port, and the proxy forwarding
 * config. Mutates cfg with the new registry entry (caller saves).
 *
 * Everything the caller passes is validated before the first byte is written, so
 * a rejected setting or JVM flag can never leave a half-built instance directory
 * behind.
 */
export async function createInstance(
	cfg: ClusterConfig,
	name: string,
	opts: CreateOptions,
): Promise<CreateResult> {
	// a detached reporter when the caller does not want progress, so the reporting
	// calls below need no branches
	const progress = opts.reporter ?? new ProgressReporter(`create ${name}`);

	const checks = progress.child("Validate request", 1);
	const fetching = progress.child("Download paper server", 6);
	const writing = progress.child("Write instance files", 2);

	// this node's work is entirely its children's, so it contributes none of its own
	progress.weighOwn(0);

	await checks.task({ start: `checking ${name}` }, async () => {
		if (managedInstances(cfg)[name] || cfg.instances[name]) {
			throw new Error(`instance "${name}" already exists`);
		}

		if (!/^[a-z0-9_-]+$/.test(name)) {
			throw new Error("instance name must be lowercase alphanumeric/-/_");
		}

		if (existsSync(join(root(), name))) {
			throw new Error(`directory ${join(root(), name)} already exists`);
		}

		const badSettings = validateSettings(opts.settings ?? {});

		if (badSettings.length) {
			throw new Error(badSettings.map((problem) => problem.error).join("; "));
		}

		const badArgs = validateJavaArgs(opts.javaArgs ?? []);

		if (badArgs) {
			throw new Error(badArgs);
		}
	});

	const dir = join(root(), name);
	const port = opts.port ?? nextFreePort(cfg, cfg.serverPortRange);

	const build = await fetching.task(
		{
			start: `resolving newest paper ${opts.mcVersion} build`,
			done: `paper ${opts.mcVersion} downloaded`,
			failed: `could not download paper ${opts.mcVersion}`,
		},
		async (step) => {
			const info = await papermc.latestBuild("paper", opts.mcVersion);

			await mkdir(join(dir, "plugins"), { recursive: true });
			await mkdir(join(dir, "config"), { recursive: true });

			step.info(0.05, `build ${info.build} — starting download`);

			await papermc.downloadBuild(info, join(dir, "server.jar"), (received, total) => {
				const mb = (received / 1024 / 1024).toFixed(1);

				// with no content-length there is nothing to divide by, so the step
				// only reports the byte count and its progress stays where it was
				if (!total) {
					step.info(step.progress, `build ${info.build} — ${mb} MB`);

					return;
				}

				const ratio = received / total;

				step.info(
					0.05 + ratio * 0.95,
					`build ${info.build} — ${mb} / ${(total / 1024 / 1024).toFixed(1)} MB`,
				);
			});

			return info;
		},
	);

	await writing.task(
		{ start: "writing eula, properties and forwarding config", done: "instance files written" },
		async (step) => {
			await Bun.write(join(dir, "eula.txt"), "eula=true\n");
			step.info(0.3, "eula accepted");

			await Bun.write(
				join(dir, "server.properties"),
				serverPropertiesTemplate(port, opts.settings ?? {}, opts.daemon ? "0.0.0.0" : "127.0.0.1"),
			);
			step.info(0.6, `server.properties on port ${port}`);

			const secret = await readForwardingSecret(cfg);

			await Bun.write(join(dir, "config", "paper-global.yml"), paperGlobalTemplate(secret));
			step.info(0.9, "velocity modern forwarding keyed");
		},
	);

	const inst: InstanceConfig = {
		dir: name,
		software: "paper",
		mcVersion: opts.mcVersion,
		port,
		memory: opts.memory ?? "2G",
		profile: opts.profile ?? "aikar",
		proxy: { register: opts.register ?? true },
	};

	if (opts.javaArgs?.length) {
		inst.javaArgs = opts.javaArgs;
	}

	if (opts.pluginGroups?.length) {
		inst.pluginGroups = opts.pluginGroups.filter((group) => group !== "default");
	}

	if (opts.pluginOverrides && Object.keys(opts.pluginOverrides).length) {
		inst.pluginOverrides = opts.pluginOverrides;
	}

	if (opts.daemon) {
		inst.daemon = opts.daemon;
	}

	cfg.instances[name] = inst;

	return { name, dir, port, build };
}

export interface SetVersionResult {
	from?: string;
	to: string;
	build: papermc.BuildInfo;
	backedUpJar: string;
}

/**
 * Swap an instance onto another Minecraft version, keeping the previous jar as
 * `.old` and rolling back to it if the download fails. Mutates cfg (caller saves).
 */
export async function setVersion(
	cfg: ClusterConfig,
	name: string,
	mcVersion: string,
	reporter?: ProgressReporter,
): Promise<SetVersionResult> {
	const inst = managedInstances(cfg)[name];

	if (!inst) {
		throw new Error(`unknown instance: ${name}`);
	}

	const progress = reporter ?? new ProgressReporter(`set-version ${name}`);
	const project = inst.software === "velocity" ? "velocity" : "paper";

	progress.info(0.05, `resolving newest ${project} ${mcVersion} build`);

	const build = await papermc.latestBuild(project, mcVersion);
	const jar = join(instanceDir(inst), inst.software === "velocity" ? "velocity.jar" : "server.jar");
	const backup = jar + ".old";

	if (existsSync(jar)) {
		await rm(backup, { force: true });
		await rename(jar, backup);
	}

	try {
		await papermc.downloadBuild(build, jar, (received, total) => {
			const mb = (received / 1024 / 1024).toFixed(1);

			if (!total) {
				progress.info(progress.progress, `build ${build.build} — ${mb} MB`);

				return;
			}

			progress.info(
				0.1 + (received / total) * 0.85,
				`build ${build.build} — ${mb} / ${(total / 1024 / 1024).toFixed(1)} MB`,
			);
		});
	} catch (err) {
		progress.error(progress.progress, "download failed — rolled back to the previous jar");

		if (existsSync(backup)) {
			await rename(backup, jar);
		}

		throw err;
	}

	const from = inst.mcVersion;

	inst.mcVersion = mcVersion;

	progress.complete(`${from ?? "?"} → ${mcVersion} (build ${build.build})`);

	return { from, to: mcVersion, build, backedUpJar: backup };
}

/**
 * Replace an instance's custom JVM flags. Registry only — the flags reach the
 * server through the run script, which is regenerated on every start.
 */
export function setJavaArgs(cfg: ClusterConfig, name: string, args: string[]): void {
	const inst = managedInstances(cfg)[name];

	if (!inst) {
		throw new Error(`unknown instance: ${name}`);
	}

	const problem = validateJavaArgs(args);

	if (problem) {
		throw new Error(problem);
	}

	if (args.length) {
		inst.javaArgs = args;
	} else {
		delete inst.javaArgs;
	}
}

/** Change an instance's game port (server.properties + registry; caller runs proxy sync). */
export async function setPort(cfg: ClusterConfig, name: string, port: number): Promise<void> {
	const inst = managedInstances(cfg)[name];

	if (!inst) {
		throw new Error(`unknown instance: ${name}`);
	}

	if (inst.software === "paper") {
		const props = join(instanceDir(inst), "server.properties");

		if (!(await setConfValue(props, "properties", "server-port", port))) {
			throw new Error(`could not update server-port in ${props}`);
		}
	}

	inst.port = port;
}

/** Read one key from an instance's server.properties. */
export async function getServerProperty(
	cfg: ClusterConfig,
	name: string,
	key: string,
): Promise<string | undefined> {
	const inst = managedInstances(cfg)[name];

	if (!inst) {
		throw new Error(`unknown instance: ${name}`);
	}

	return await getConfValue(join(instanceDir(inst), "server.properties"), "properties", key);
}

/** Write one key into an instance's server.properties. False when the key is absent. */
export async function setServerProperty(
	cfg: ClusterConfig,
	name: string,
	key: string,
	value: string,
): Promise<boolean> {
	const inst = managedInstances(cfg)[name];

	if (!inst) {
		throw new Error(`unknown instance: ${name}`);
	}

	return await setConfValue(
		join(instanceDir(inst), "server.properties"),
		"properties",
		key,
		value,
	);
}

/**
 * Drop an instance from the registry, optionally deleting its directory too.
 * External instances are never purged — their files live on another machine.
 * A purge deletes the directory entry by entry so the reporter can say which
 * part of a multi-gigabyte world is currently going.
 */
export async function deleteInstance(
	cfg: ClusterConfig,
	name: string,
	purge: boolean,
	reporter?: ProgressReporter,
): Promise<{ purged: boolean }> {
	const progress = reporter ?? new ProgressReporter(`delete ${name}`);
	const inst = cfg.instances[name];

	if (!inst) {
		throw new Error(`unknown instance: ${name}`);
	}

	progress.info(0.05, "deregistering from the cluster");
	delete cfg.instances[name];

	if (purge && !inst.external) {
		const dir = instanceDir(inst);
		let entries: string[] = [];

		try {
			entries = await readdir(dir);
		} catch {
			// the directory is already gone — nothing left to purge
		}

		for (let i = 0; i < entries.length; i++) {
			progress.info(0.1 + (i / Math.max(1, entries.length)) * 0.85, `deleting ${entries[i]}`);

			await rm(join(dir, entries[i]!), { recursive: true, force: true });
		}

		await rm(dir, { recursive: true, force: true });
	}

	progress.complete(
		purge && !inst.external ? "directory deleted" : "deregistered — directory kept",
	);

	return { purged: purge };
}
