// Copyright (c) 2026 Belikhun. All rights reserved.
// Proprietary software: use, copying, modification and distribution are
// prohibited without written permission. See LICENSE at the repository root.

import { chmod, rm } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";

import type { ClusterConfig, InstanceConfig } from "./types";
import { instanceDir, managedInstances } from "./config";
import { renderManagedFiles } from "./configfiles";
import { ENV_SCRIPT, loadEnv, renderEnvFile, resolveVars } from "./environment";
import * as screen from "./screen";
import { ping } from "./ping";
import { t } from "../shared/i18n";

export const NORESTART = ".luna-norestart";

const RUN_SCRIPT = "run.sh";

/** Screen session name for an instance, e.g. `luna.lobby`. */
export function sessionName(cfg: ClusterConfig, name: string): string {
	return cfg.screenPrefix + name;
}

/** File name of the server jar inside the instance directory. */
export function jarName(inst: InstanceConfig): string {
	return inst.software === "velocity" ? "velocity.jar" : "server.jar";
}

/** Console command that shuts this software down gracefully. */
export function stopCommand(inst: InstanceConfig): string {
	return inst.software === "velocity" ? "end" : "stop";
}

/**
 * NeoForge's generated argument file, relative to the instance directory. The
 * installer writes the whole classpath and launch target in there, so it is the
 * only supported way to boot the server; there is no runnable `-jar`.
 */
export function neoForgeArgsFile(inst: InstanceConfig): string {
	if (!inst.loaderVersion) {
		throw new Error(t("core.instances.noLoaderVersion"));
	}

	return `libraries/net/neoforged/neoforge/${inst.loaderVersion}/unix_args.txt`;
}

/**
 * Assemble the full java invocation for an instance from its java profile.
 *
 * Paper and velocity launch from a jar. NeoForge instead launches from the
 * installer's argument file, which already carries the classpath and the launch
 * target, so luna contributes only the heap, the profile's flags and `nogui`
 * (bare, not `--nogui`: modlauncher takes it as a program argument). The pack's
 * own `user_jvm_args.txt` is deliberately not referenced, because memory and
 * flags come from the registry.
 */
export function buildJavaCommand(cfg: ClusterConfig, inst: InstanceConfig): string {
	const profile = cfg.javaProfiles[inst.profile];

	if (!profile) {
		throw new Error(t("core.instances.unknownProfile", { name: inst.profile }));
	}

	const java = inst.java ?? profile.java ?? "java";

	const parts = [
		java,
		`-Xms${inst.memory}`,
		`-Xmx${inst.memory}`,
		...profile.flags,
		// per-instance flags last, so they win over the profile's defaults for any
		// option the JVM resolves by last-one-wins
		...(inst.javaArgs ?? []),
	];

	if (inst.software === "neoforge") {
		parts.push(`@${neoForgeArgsFile(inst)}`, "nogui");
	} else {
		parts.push("-jar", jarName(inst));

		if (inst.software === "paper") {
			parts.push("--nogui");
		}
	}

	if (profile.jarArgs) {
		parts.push(...profile.jarArgs);
	}

	return parts.join(" ");
}

/**
 * Write the instance's environment file from the store, resolved for this
 * instance (builtin < global < machine < instance). Regenerated on every start
 * so a variable change needs nothing but a restart, and 0600 because the
 * resolved set includes whatever the operator marked secret.
 */
export async function writeEnvFile(cfg: ClusterConfig, name: string): Promise<string> {
	const inst = managedInstances(cfg)[name];

	if (!inst) {
		throw new Error(t("core.instances.unknown", { name }));
	}

	const vars = await resolveVars(cfg, await loadEnv(), name);
	const path = join(instanceDir(inst), ENV_SCRIPT);

	await Bun.write(path, renderEnvFile(vars));
	await chmod(path, 0o600);

	return path;
}

/** Generate the instance run script (auto-restart loop with stop sentinel + crash-loop guard). */
export async function writeRunScript(cfg: ClusterConfig, name: string): Promise<string> {
	const inst = managedInstances(cfg)[name];

	if (!inst) {
		throw new Error(t("core.instances.unknown", { name }));
	}

	const script = `#!/bin/bash
# Generated by luna. Do not edit; it is regenerated on every start.
cd "$(dirname "$0")" || exit 1
rm -f ${NORESTART}

# Environment manager (luna env): every variable the instance resolves, exported
# into the JVM's environment. Written beside this script on every start.
if [ -f ${ENV_SCRIPT} ]; then
    . ./${ENV_SCRIPT}
fi

CRASH_WINDOW=300
CRASH_MAX=3
crashes=()

while true; do
    ${buildJavaCommand(cfg, inst)}
    code=$?

    if [ -f ${NORESTART} ]; then
        rm -f ${NORESTART}
        echo "[luna] stop requested, not restarting."
        exit 0
    fi

    now=$(date +%s)
    recent=()
    for t in "\${crashes[@]}"; do
        [ $(( now - t )) -lt $CRASH_WINDOW ] && recent+=("$t")
    done
    crashes=("\${recent[@]}" "$now")
    if [ "\${#crashes[@]}" -ge "$CRASH_MAX" ]; then
        echo "[luna] crash loop detected (\${#crashes[@]} exits in \${CRASH_WINDOW}s), staying down."
        exit 1
    fi

    echo "[luna] server exited (code $code), restarting in 3s. Ctrl+C to abort."
    sleep 3
done
`;

	const path = join(instanceDir(inst), RUN_SCRIPT);

	await Bun.write(path, script);
	await chmod(path, 0o755);

	return path;
}

export interface InstanceStatus {
	name: string;
	inst: InstanceConfig;
	/** stopped = no session; starting = session+process but no ping; running =
	 *  answers pings; unknown = owned by an unreachable follower daemon */
	state: "stopped" | "starting" | "running" | "unknown";
	javaPid?: number;
	uptimeMs?: number;
	players?: { online: number; max: number };
	pingVersion?: string;
}

/**
 * Live state of one instance: whether its session and java process exist, and
 * whether the server answers a status ping (the difference between "starting"
 * and "running").
 */
export async function getStatus(cfg: ClusterConfig, name: string): Promise<InstanceStatus> {
	const inst = managedInstances(cfg)[name]!;
	const dir = instanceDir(inst);
	const session = sessionName(cfg, name);

	const [hasSession, pid] = await Promise.all([
		screen.sessionExists(session),
		screen.javaPidFor(dir),
	]);

	const up = hasSession && pid !== undefined;

	const status: InstanceStatus = {
		name,
		inst,
		state: up ? "starting" : "stopped",
		javaPid: pid,
	};

	if (pid) {
		const started = await screen.processStartTime(pid);

		if (started) {
			status.uptimeMs = Date.now() - started.getTime();
		}
	}

	if (up) {
		const pong = await ping("127.0.0.1", inst.port);

		if (pong) {
			status.state = "running";
			status.players = { online: pong.online, max: pong.max };
			status.pingVersion = pong.version;
		}
	}

	return status;
}

/** Live state of every managed instance, probed in parallel. */
export async function getAllStatuses(cfg: ClusterConfig): Promise<InstanceStatus[]> {
	const names = Object.keys(managedInstances(cfg));

	return await Promise.all(names.map((name) => getStatus(cfg, name)));
}

/** Start an instance in its screen session, regenerating its run script first. */
export async function startInstance(
	cfg: ClusterConfig,
	name: string,
): Promise<"started" | "already-running"> {
	const inst = managedInstances(cfg)[name];

	if (!inst) {
		throw new Error(t("core.instances.unknown", { name }));
	}

	const session = sessionName(cfg, name);

	if (await screen.sessionExists(session)) {
		return "already-running";
	}

	// everything derived from the registry and the env store is rebuilt here, so a
	// start is what converges the instance onto the current state: the env file the
	// JVM inherits, the managed config files rendered from their templates, then
	// the run script that ties them together
	await writeEnvFile(cfg, name);
	await renderManagedFiles(cfg, name);

	const script = await writeRunScript(cfg, name);

	await screen.startDetached(session, script, instanceDir(inst));

	return "started";
}

export interface StopResult {
	outcome: "stopped" | "not-running" | "forced";
	tookMs: number;
}

/**
 * Stop an instance gracefully: drop the no-restart sentinel so the wrapper loop
 * exits, ask the server to shut itself down, then escalate to SIGTERM and to
 * killing the session if it overruns `timeoutMs`. Idempotent: stopping an
 * already-stopped instance reports "not-running" and touches nothing.
 */
export async function stopInstance(
	cfg: ClusterConfig,
	name: string,
	timeoutMs = 120_000,
): Promise<StopResult> {
	const inst = managedInstances(cfg)[name];

	if (!inst) {
		throw new Error(t("core.instances.unknown", { name }));
	}

	const dir = instanceDir(inst);
	const session = sessionName(cfg, name);
	const started = Date.now();

	if (!(await screen.sessionExists(session))) {
		return { outcome: "not-running", tookMs: 0 };
	}

	// Sentinel first so the wrapper loop exits instead of restarting.
	await Bun.write(join(dir, NORESTART), "");

	const pid = await screen.javaPidFor(dir);
	let forced = false;

	if (pid !== undefined) {
		await screen.stuff(session, stopCommand(inst));

		while (Date.now() - started < timeoutMs) {
			const alive = await screen.javaPidFor(dir);

			if (alive === undefined || alive !== pid) {
				break;
			}

			await Bun.sleep(500);
		}

		if ((await screen.javaPidFor(dir)) === pid) {
			process.kill(pid, "SIGTERM");
			await Bun.sleep(3000);
			forced = true;
		}
	}

	// Wait for the wrapper to exit on its own, then make sure the session is gone.
	for (let i = 0; i < 20 && (await screen.sessionExists(session)); i++) {
		await Bun.sleep(250);
	}

	if (await screen.sessionExists(session)) {
		await screen.quit(session);
	}

	// Kill any respawned java (legacy start loop won the race): <1s old, pre-world-load.
	const respawned = await screen.javaPidFor(dir);

	if (respawned !== undefined && respawned !== pid) {
		try {
			process.kill(respawned, "SIGTERM");
		} catch {
			// it exited on its own between the lookup and the signal
		}
	}

	const sentinel = join(dir, NORESTART);

	if (existsSync(sentinel)) {
		await rm(sentinel, { force: true });
	}

	return {
		outcome: forced ? "forced" : "stopped",
		tookMs: Date.now() - started,
	};
}

/** Order for --all operations: proxy first on start, proxy last on stop. */
export function orderedNames(cfg: ClusterConfig, mode: "start" | "stop"): string[] {
	const names = Object.keys(managedInstances(cfg));
	const backends = names.filter((name) => name !== "proxy").sort();

	return mode === "start" ? ["proxy", ...backends] : [...backends, "proxy"];
}

/** Send an arbitrary console command to a running instance. */
export async function sendCommand(
	cfg: ClusterConfig,
	name: string,
	cmd: string,
): Promise<boolean> {
	const session = sessionName(cfg, name);

	if (!(await screen.sessionExists(session))) {
		return false;
	}

	await screen.stuff(session, cmd);

	return true;
}
