// Copyright (c) 2026 Belikhun. All rights reserved.
// Proprietary software: use, copying, modification and distribution are
// prohibited without written permission. See LICENSE at the repository root.

/**
 * The web maps luna can serve, and what each one is shaped like.
 *
 * Two of them exist, they solve the same problem and they agree on almost
 * nothing: BlueMap is a WebGL application reading a directory of its own binary
 * tiles, Dynmap is a Leaflet page reading a tree of JPEGs. What luna needs from
 * either is the same four facts - which addon ships it, which port its own
 * webserver binds, where the rendered files sit, and which requests only the
 * running server can answer - so those four are what this registry holds and
 * everything above it is provider-agnostic.
 *
 * A third map is a new entry here plus a `PORT_PRESETS` entry, and nothing else.
 */

import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { isAbsolute, join, resolve } from "node:path";

/** Maps luna knows how to serve. */
export type MapProviderId = "bluemap" | "dynmap";

/** What one map provider is, from luna's side of it. */
export interface MapProviderSpec {
	id: MapProviderId;
	/** Addon provider slug that ships it, which is how a lock entry is recognised */
	slug: string;
	/**
	 * Directories its own configuration sits in, relative to the instance.
	 *
	 * Several, because the same addon is a plugin on one platform and a mod on
	 * another: paper keeps its files under `plugins/`, the loaders elsewhere.
	 */
	configDirs: readonly string[];
	/** Config files carrying the webroot key, most authoritative first */
	configFiles: readonly string[];
	/** Key naming the webroot inside those files */
	webrootKey: string;
	/**
	 * What the webroot value is relative to: the instance directory (BlueMap
	 * writes `bluemap/web`, counted from where the server runs) or the config
	 * directory itself (Dynmap writes `web`, counted from its own data dir).
	 */
	webrootBase: "instance" | "config";
	/** Webroot when the config says nothing, in the same terms as `webrootBase` */
	webrootDefault: string;
	/** Document the embed loads, and the proof a directory holds a webapp at all */
	index: string;
	/**
	 * A file that exists only when the rendered webroot can boot on its own.
	 *
	 * Absent for a provider whose webapp always reads plain files. Dynmap's does
	 * not: in its default mode the page's own configuration is generated by the
	 * plugin's webserver per request, so the files on disk are a map nobody can
	 * open. `JsonFileClientUpdateComponent` is what writes them down, and this is
	 * the file it writes.
	 */
	offlineMarker?: string;
	/**
	 * Config line that must be present, and uncommented, for those files to keep
	 * being written.
	 *
	 * The marker alone lies. Dynmap leaves its json-file output behind when the
	 * component that wrote it is switched off, so a webroot can hold a bootstrap
	 * naming documents that stopped being updated - a map that loads and shows a
	 * frozen world while reporting itself fit to serve. Requiring the component too
	 * is the difference between "these files exist" and "these files are current".
	 */
	offlineRequires?: RegExp;
	/** Requests only the running server can answer */
	livePath: RegExp;
	/**
	 * Requests the rendered files must answer even while the plugin is running.
	 *
	 * There is exactly one reason to need this and Dynmap has it: the file that
	 * tells its webapp where to read everything else. Dynmap's webserver generates
	 * that file per request and always names its own in-memory endpoints, while the
	 * copy on disk names the written ones - so serving the generated version points
	 * the page at endpoints that stop existing the moment the server does, which is
	 * a map that works until it matters. Taking it from disk pins the page to the
	 * written files, which are refreshed every second while the server runs and stay
	 * put afterwards.
	 *
	 * Falls through to the live answer when the file is absent, which is how an
	 * instance still running the internal update component keeps working.
	 */
	preferFile?: RegExp;
	/** Where a missing file is a normal answer rather than an error: empty tiles */
	emptyPath: RegExp;
}

/** Every provider, in the order they are looked for. */
export const MAP_PROVIDERS: readonly MapProviderSpec[] = [
	{
		id: "bluemap",
		slug: "bluemap",
		configDirs: ["plugins/BlueMap", "config/bluemap"],
		configFiles: ["webapp.conf", "webserver.conf"],
		webrootKey: "webroot",
		webrootBase: "instance",
		webrootDefault: "bluemap/web",
		index: "index.html",
		// its `settings.json` and every tile are plain files; only the player and
		// marker feeds come from the plugin
		livePath: /^maps\/[^/]+\/live\//,
		emptyPath: /^maps\/[^/]+\/tiles\//,
	},

	{
		id: "dynmap",
		slug: "dynmap",
		configDirs: ["plugins/dynmap", "dynmap", "config/dynmap"],
		configFiles: ["configuration.txt"],
		webrootKey: "webpath",
		webrootBase: "config",
		webrootDefault: "web",
		index: "index.html",
		offlineMarker: "standalone/config.js",
		offlineRequires: /^[ \t]*-[ \t]*class:[ \t]*org\.dynmap\.JsonFileClientUpdateComponent[ \t]*$/m,
		preferFile: /^standalone\/config\.js$/,
		// the `up/` tree is the internal update component, which is the plugin
		// answering out of memory; in json-file mode the page never asks for it
		livePath: /^up\//,
		emptyPath: /^tiles\//,
	},
];

/** The provider a lock entry's addon slug names, if any. */
export function mapProviderOfSlug(slug: string | undefined): MapProviderSpec | undefined {
	return slug ? MAP_PROVIDERS.find((provider) => provider.slug === slug) : undefined;
}

/** One provider by id; the console sends an id and gets the shape back. */
export function mapProvider(id: MapProviderId): MapProviderSpec {
	return MAP_PROVIDERS.find((provider) => provider.id === id)!;
}

/** Where one provider's rendered files sit, and whether they can stand alone. */
export interface MapWebroot {
	provider: MapProviderId;
	/** Absolute path of the webroot on this machine */
	dir: string;
	/**
	 * Whether the webapp in it boots without the server running.
	 *
	 * False is a real map that is only reachable live, which is a thing to report
	 * rather than a thing to hide: the operator can change it, and until they do,
	 * a stopped instance has no map.
	 */
	offlineReady: boolean;
}

/**
 * Resolve a provider's rendered webroot on this machine's disk.
 *
 * A rendered map is a directory of files, so it does not need the server that
 * produced it: the tiles, the webapp and its settings are all sitting there
 * whether the instance is running or not. That is what lets the console keep
 * serving a map for a stopped instance, and it is why this is resolved from disk
 * rather than from the registry.
 *
 * Local by definition: it answers about the machine it runs on, which is the
 * owner once the call has been routed there. Undefined when the provider was
 * never configured, or when nothing has been rendered yet - a directory without
 * the webapp's own index is not a map.
 */
export async function resolveMapWebroot(
	instanceDir: string,
	provider: MapProviderSpec,
): Promise<MapWebroot | undefined> {
	for (const configDir of provider.configDirs) {
		const base = join(instanceDir, configDir);

		if (!existsSync(base)) {
			continue;
		}

		const config = await readConfig(base, provider);
		const value = configuredWebroot(config, provider);
		const from = provider.webrootBase === "config" ? base : instanceDir;
		const dir = isAbsolute(value) ? resolve(value) : resolve(from, value);

		if (!existsSync(join(dir, provider.index))) {
			continue;
		}

		const written = !provider.offlineMarker || existsSync(join(dir, provider.offlineMarker));
		const current = !provider.offlineRequires || provider.offlineRequires.test(config);

		return {
			provider: provider.id,
			dir,
			offlineReady: written && current,
		};
	}

	return undefined;
}

/**
 * The first of a provider's config files that reads, or an empty string.
 *
 * One read serves both questions asked of it - where the webroot is, and whether
 * the provider is configured to keep its files current - so the file is not
 * opened twice.
 */
async function readConfig(base: string, provider: MapProviderSpec): Promise<string> {
	for (const file of provider.configFiles) {
		const path = join(base, file);

		if (!existsSync(path)) {
			continue;
		}

		try {
			return await readFile(path, "utf8");
		} catch {
			continue;
		}
	}

	return "";
}

/**
 * The webroot key from a provider's own configuration, or its default.
 *
 * Read with a regex rather than a parser: the value wanted is one possibly
 * quoted string, the two file formats involved (HOCON and Dynmap's YAML) both
 * write it the same way, and pulling in a parser for each would be the larger
 * risk. Commented-out lines are the defaults the plugin shipped, so only an
 * uncommented one counts.
 */
function configuredWebroot(config: string, provider: MapProviderSpec): string {
	const key = provider.webrootKey.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
	const match = new RegExp(`^[ \\t]*${key}[ \\t]*[:=][ \\t]*"?([^"\\r\\n]+?)"?[ \\t]*$`, "m").exec(config);

	return match?.[1] || provider.webrootDefault;
}
