/**
 * Build identity of this binary.
 *
 * Regenerated by `scripts/genversion.ts` on every `bun run build`, so a
 * compiled daemon can state exactly which build it is; that is the value a
 * follower compares against when deciding whether an upgrade is an upgrade
 * (DESIGN.md §4.7). The checked-in values are what a from-source run reports.
 */

export const VERSION = "1.5.17";

/** Short git SHA of the tree the binary was built from, "dev" from source. */
export const COMMIT = "dev";

/** ISO 8601 build timestamp, empty from source. */
export const BUILD_AT = "";

/** The full build identity, e.g. "1.0.0+6ee20ac". */
export function buildVersion(): string {
	return COMMIT ? `${VERSION}+${COMMIT}` : VERSION;
}

/**
 * Platform triple of the running process. A binary from another platform can
 * never be a valid upgrade, so the two ends compare this before transferring
 * 90-odd megabytes.
 */
export function buildPlatform(): string {
	return `${process.platform}-${process.arch}`;
}

/**
 * Whether this process is the compiled single-file binary rather than a
 * from-source run. It decides whether self-upgrade is even possible: under
 * `bun run src/cli/index.ts`, `process.execPath` is the *bun* interpreter, and
 * overwriting that would take the machine's whole toolchain with it.
 */
export function isCompiledBinary(): boolean {
	return Bun.main.startsWith("/$bunfs/");
}
